import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import PlotControls from "@/components/PlotControls";

export const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans"
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<div className="container mx-auto">
					<div className="grid grid-rows-[auto_1fr] grid-cols-1 gap-8 p-5">
						<div>
							<PlotControls />
						</div>
						<main>{children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
